language: cpp
dist: bionic

env:
  global:
    - VIPS_VERSION=8.9.2
    - VIPS_WARNING=0
    - JOBS=`nproc`
    - LD_LIBRARY_PATH=$HOME/vips/lib:$LD_LIBRARY_PATH
    - PKG_CONFIG_PATH=$HOME/vips/lib/pkgconfig:$PKG_CONFIG_PATH
    - PATH=$HOME/vips/bin:$HOME/nginx/sbin:$PATH
    - CTEST_OUTPUT_ON_FAILURE=1
    - CTEST_PARALLEL_LEVEL=$JOBS
    - CODECOV_TOKEN=a795bded-831b-4799-a7c4-f86096834d1b

cache:
  directories:
    - $HOME/vips

addons:
  apt:
    update: true
    sources:
      # for Test::Nginx
      - sourceline: 'deb http://openresty.org/package/ubuntu $(lsb_release -cs) main'
        key_url: 'https://openresty.org/package/pubkey.gpg'
      # add support for HEIF files
      - sourceline: 'ppa:strukturag/libheif'
      - sourceline: 'ppa:strukturag/libde265'
    packages:
      # main dependencies
      - libcfitsio-dev
      - libexif-dev
      - libexpat1-dev
      - libfftw3-dev
      - libgif-dev
      - libgsf-1-dev
      - libgsl-dev
      - libheif-dev
      - liblcms2-dev
      - libmagickwand-dev
      - libmatio-dev
      - libnifti-dev
      - libopenexr-dev
      - libopenslide-dev
      - liborc-0.4-dev
      - libpango1.0-dev
      - libpng-dev
      - libpoppler-glib-dev
      - librsvg2-dev
      - libtiff5-dev
      - libwebp-dev
      # needed for building libvips from source
      - gtk-doc-tools
      - gobject-introspection
      # needed for the integration tests
      - libtest-nginx-perl
      # needed for code coverage
      - lcov

install:
  - |
    bash .ci/install-vips.sh \
      --disable-dependency-tracking

script:
  - mkdir -p build && cd build
  - |
    cmake .. \
      -DCMAKE_BUILD_TYPE=Debug \
      -DCUSTOM_NGX_FLAGS="--prefix=$HOME/nginx" \
      -DENABLE_COVERAGE=ON \
      -DBUILD_TESTS=ON
  - make -j$JOBS
  - make test
  - TEST_NGINX_SERVROOT=$PWD/servroot prove -r ../test/nginx

after_success:
  # collect coverage information
  - make coverage
  # upload coverage report to Codecov
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
